name: Gatsby Publish

on:
  push:
    branches:
      - main  # デプロイをトリガーするブランチを指定します

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1'  # 使用するNode.jsのバージョンを指定します

    - name: Install Dependencies
      run: npm install

    - name: Show npm debug log
      if: failure()  # このステップはジョブが失敗したときのみ実行されます
      run: cat /home/runner/.npm/_logs/*-debug.log

    - name: Build
      run: npm run build  # Gatsbyのビルドコマンドを実行します

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Gatsbyのビルド結果が格納されるディレクトリを指定します