name: Gatsby Publish

on:
  push:
    branches:
      - main  # デプロイをトリガーするブランチを指定します
   
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1'  # 使用するNode.jsのバージョンを指定します

    - name: Install Dependencies
      run: npm install

    - name: Show npm debug log
      if: failure()  # このステップはジョブが失敗したときのみ実行されます
      run: cat /home/runner/.npm/_logs/*-debug-*.log

    - name: Build
      run: npm run build  # Gatsbyのビルドコマンドを実行します

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4